### ISSUE TITLE
COPYING file specifices GPL3 is this correct?

### ISSUE THREAD

**Issue by jspashett** [kmarkus/rFSM#15]
The COPYING file specifies GPL3, but the READme.md says "rFSM is dual licensed under LGPL/BSD."

and the headers (at least some of them say GPL-2.

Can we get some clarity on this, and perhaps update the COPYING file.

**Comment by kmarkus** [comment]
Hi,

The GPL3 `COPYING` is indeed a mistake, the correct license is indeed dual LGPL/BSD. I'm a little surprised nobody noticed this before. I will fix this, thanks for reporting!

**Comment by jspashett** [comment]
Thanks Markus, 

My client is considering using the library in a product. It it is possible they might make some small contributions, so would raise pull requests with these - but I note that there are 5 outstanding pull requests, perhaps you are no longer accepting them for this project?

**Comment by kmarkus** [comment]
I am accepting pull requests, I just didn't get around for a while so there's some catching up to do...

**Comment by kmarkus** [comment]
> Hi,
> 
> The GPL3 `COPYING` is indeed a mistake, the correct license is dual LGPL/BSD. I'm a little surprised nobody noticed this before. I will fix this, thanks for reporting!

**Comment by kmarkus** [comment]
I've pushed a fix, please let me know if you find any more inconsistencies. Thanks for reporting!
