### ISSUE TITLE
adding an event to an 'initial' transition causes rFSM to stall, without throwing an error

### ISSUE THREAD

**Issue by dvanthienen** [kmarkus/rFSM#9]
Adding an event to an 'initial' transition causes rFSM to stall, without throwing an error.
For example rfsm.trans{src="initial", tgt="stateA", events={"e_done"}}.
Especially when this transition is part of a hierachical FSM:
uplevel = rfsm.state{
stateAA=rfsm.state{},
stateBB=rfsm.state{
  stateA = rfsm.state{},
  rfsm.trans{src="initial", tgt="stateA", events={"e_done"}},
},
rfsm.trans{src="initial", tgt="stateAA"},
rfsm.trans{src="stateAA", tgt="stateBB", events={"e_done"}}
}

rFSM does not make the exit of the previous state (state AA), just stays in this state.
There is no hint whatsoever that it is a transition in a next sub-state that causes the error.
 Especially annoying when the sub-states are in different files...

**Comment by kmarkus** [comment]
Hi Nick

"e_done" is syntactic sugar and expands to "e_done@fqn", fqn being the source state fully qualified name. When the entry and doo of a state complete, this event will be raised. But for the initial connector no such event is raised (a connector doesn't have any behavior) so you get stuck. In short, it's illegal to add events (or guards for that matter) to initial transitions. This should be checked for and raise an error.

**Comment by dvanthienen** [comment]
Hi Markus,

Who should check this?
By checking conformity of the model wrt. the umf meta-model?
Is this still up-to-date and does it include this check?

thx for following up :)

Nick

**Comment by kmarkus** [comment]
On Mo, Okt 19, 2015 at 01:18:50 -0700, Dominick Vanthienen wrote:
>Hi Markus,
>
>Who should check this?

The rFSM validation code...

>By checking conformity of the model wrt. the umf meta-model?

Right, but this is manually implemented, no formal model checking a la uMF.

>Is this still up-to-date and does it include this check?

Is what up to date? It currently doesn't check ....

>thx for following up :)

You're welcome!

Best regards
Markus
